### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by sanet1313** [Lonrix-Limited/jcass_toolbox_releases#1]
Please correct the third type of model under BCA Optimisation Methods - there are two "bca-egal' tags

[Link to page is here](https://lonrix-limited.github.io/jcass_docs2/inputs/meta_file.html#bca_optimisation_method)

**Comment by fritzjoostenz** [comment]
@sanet1313 - thanks for reporting this issue. I will work on it with energy and devotion.

**Comment by fritzjoostenz** [comment]
@sanet1313 - this should now be fixed
